ESRI-239 - Redesign of Login Page
cyclomedia/streetsmart-arcgis-pro pull request #143
Opened 2024-10-11 14:45 UTC by AleksaMilivojevicCycloMedia

ESRI-239 - Redesign of Login Page

2024-10-14 09:03 UTC, bervacanin-cy requested changes

2024-10-14 09:03 UTC, bervacanin-cy commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/AddIns/Pages/Login.cs
> +      //_login.IsOAuth = _isOAuth;
Do not leave commented source code.

2024-10-14 09:03 UTC, bervacanin-cy commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/AddIns/Pages/Login.cs
> +      NotifyPropertyChanged("Username");
Double check why is this needed here.

2024-10-14 09:03 UTC, bervacanin-cy commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/AddIns/Views/Converters/BasicAuthLoggedInConverter.cs
> +  class BasicAuthLoggedInConverter : IValueConverter
Name is unclear

2024-10-14 09:03 UTC, bervacanin-cy commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/AddIns/Views/Converters/BasicAuthLoggedInConverter.cs
> +      return 2;
Return values are unclear.

2024-10-14 09:03 UTC, bervacanin-cy commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/AddIns/Views/Converters/BasicLoginConverter.cs
> +  public class BasicLoginConverter : IValueConverter
Unclear name

2024-10-14 09:03 UTC, bervacanin-cy commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/AddIns/Views/Converters/BasicLoginRevertConverter.cs
> +    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
Unclear name

2024-10-14 09:03 UTC, bervacanin-cy commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/AddIns/Views/Converters/IsOAuthToRowConverter.cs
> +  public class IsOAuthToRowConverter : IValueConverter
Unclear name

2024-10-14 09:03 UTC, bervacanin-cy commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/AddIns/Views/Converters/LoginBasicConverter.cs
> +  public class LoginBasicConverter : IValueConverter
Unclear name

2024-10-14 09:03 UTC, bervacanin-cy commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/AddIns/Views/Converters/MarginSplitConverter.cs
> +  class MarginSplitConverter : IValueConverter
Unclear name

2024-10-14 09:03 UTC, bervacanin-cy commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/AddIns/Views/Converters/OAuthUsernameDisplayConverter.cs
> +  class OAuthUsernameDisplayConverter: IValueConverter
Unclear name

2024-10-14 09:03 UTC, bervacanin-cy commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/AddIns/Views/Converters/SignInEnabled.cs
> +using CefSharp.DevTools.CSS;
Why do we need this.

2024-10-14 09:03 UTC, bervacanin-cy commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/AddIns/Views/Login.xaml.cs
> +﻿using ArcGIS.Desktop.Internal.Mapping;
Is this needed?

2024-10-14 09:03 UTC, bervacanin-cy commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/Properties/Resources.fr.resx
> +    <value>Log out</value>
Double check if we can get all translations for fr.

2024-10-14 13:58 UTC, martin-sven-kovacic-valcon requested changes

2024-10-14 13:58 UTC, martin-sven-kovacic-valcon commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/AddIns/Pages/Login.cs
> +          IsModified = true;
why do we need this variable?

2024-10-14 13:58 UTC, martin-sven-kovacic-valcon commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/Configuration/File/Login.cs
> +          OnPropertyChanged("Credentials");
duplication

2024-10-14 14:00 UTC, martin-sven-kovacic-valcon requested changes

2024-10-14 14:00 UTC, martin-sven-kovacic-valcon commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/AddIns/Pages/Login.cs
> +      NotifyPropertyChanged("Credentials");
duplication

2024-10-14 14:01 UTC, martin-sven-kovacic-valcon commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/AddIns/Views/Login.xaml
> -            <fa:ImageAwesome Grid.Column="2" Icon="Spinner" Spin="True" Height="18" Width="18" Visibility="{Binding OAuthAuthenticationStatus, Converter={StaticResource SigningInProgressToVisibility}
where did the spinner go?

2024-10-16 13:31 UTC, martin-sven-kovacic-valcon approved these changes

2024-10-16 14:36 UTC, bervacanin-cy approved these changes

2024-10-23 08:28 UTC, merged