ESRI-235 - Proactive insights - Spam protection
cyclomedia/streetsmart-arcgis-pro pull request #145
Opened 2024-10-15 08:54 UTC by AleksaMilivojevicCycloMedia

ESRI-235 - Proactive insights - Spam protection

2024-10-15 10:42 UTC, martin-sven-kovacic-valcon approved these changes

2024-10-15 10:52 UTC, bervacanin-cy requested changes

2024-10-15 10:52 UTC, bervacanin-cy commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/Logging/EventLog.cs
> +    private static bool isLimitReachedBefore = false;
inconsistent coding styles in a single class.

2024-10-15 10:52 UTC, bervacanin-cy commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/Logging/EventLog.cs
> +    private static bool isLimitReachedBefore = false;
Reached Before what?

2024-10-15 10:52 UTC, bervacanin-cy commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/Logging/EventLog.cs
> +    private static DateTime lastReset;
Naming - last reset of what?

2024-10-15 10:52 UTC, bervacanin-cy commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/Logging/EventLog.cs
> +        isLimitReachedBefore = true;
isLimitReachedBefore = _logData.LogCount >= LogsLimit;

2024-10-15 10:52 UTC, bervacanin-cy commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/Logging/EventLog.cs
> +          if (!isLimitReachedBefore)
Remove nested ifs

2024-10-15 10:52 UTC, bervacanin-cy commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/Logging/EventLog.cs
> +    private static int LogsLimit = LogData.Instance.LogLimit;
Do we need to ensure in variable names that it is related to error logs only?

2024-10-15 10:52 UTC, bervacanin-cy commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/Logging/LogData.cs
> +  private static string LogDataFileName => Path.Combine(FileUtils.FileDir, "logdata.xml");
All other file names in this folder have Pascal Case naming.

2024-10-15 10:52 UTC, bervacanin-cy commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/Logging/LogData.cs
> +      EventLog.Write(EventLogLevel.Error, $"Street Smart: (EventLog.cs) (SaveLogData)");
Is this a circular dependency?

2024-10-15 10:52 UTC, bervacanin-cy commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/Logging/LogData.cs
> +      EventLog.Write(EventLogLevel.Error, $"Street Smart: (EventLog.cs) (LoadLogData)");
Is this a circular dependency?

2024-10-15 10:52 UTC, bervacanin-cy commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/Logging/LogData.cs
> +  public LogData(int logCount, DateTime lastResetTime, bool useSentryLogging, int logLimit, TimeUnit timeUnit)
Why do we need two constructors?

2024-10-15 11:24 UTC, martin-sven-kovacic-valcon requested changes

2024-10-15 11:24 UTC, martin-sven-kovacic-valcon commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/Logging/EventLog.cs
> +    }
this needs to be completely redone

2024-10-15 12:15 UTC, AleksaMilivojevicCycloMedia commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/Logging/LogData.cs
> +  public LogData(int logCount, DateTime lastResetTime, bool useSentryLogging, int logLimit, TimeUnit timeUnit)
We don't need two constructors here

2024-10-16 12:07 UTC, martin-sven-kovacic-valcon approved these changes

2024-10-16 12:07 UTC, martin-sven-kovacic-valcon commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/AddIns/Modules/StreetSmart.cs
> +      return Task.FromResult(0);
return Task.CompletedTask

2024-10-17 08:35 UTC, bervacanin-cy requested changes

2024-10-17 08:35 UTC, bervacanin-cy commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/Configuration/File/LogData.cs
> +        UseSentryLogging = true,
I think we should avoid having Sentry enabled by default. We still do not have a company account.

2024-10-17 08:41 UTC, AleksaMilivojevicCycloMedia commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/Configuration/File/LogData.cs
> +        UseSentryLogging = true,
I agree, i will change it to disabled

2024-10-17 08:56 UTC, bervacanin-cy approved these changes

2024-10-23 07:55 UTC, merged