Esri 129
cyclomedia/streetsmart-arcgis-pro pull request #68
Opened 2024-06-12 13:13 UTC by AleksaMilivojevicCycloMedia

The issue causing the application to crash when opening a feature class in a non-measurement map type has been fixed.

2024-06-12 13:45 UTC, bervacanin-cy requested changes

2024-06-12 13:45 UTC, bervacanin-cy commented on client-side/C#/StreetSmartArcGISPro/StreetSmartArcGISPro/Overlays/Measurement/MeasurementList.cs
> +    public static string GetSrsUnit(string srsString)
Please, make this method returning an enum, not string. Double check if these units already exist in source code.

2024-06-12 14:10 UTC, bervacanin-cy approved these changes

2024-06-17 12:46 UTC, Harm73 approved these changes

2024-06-17 12:46 UTC, merged